# Generated by Django 2.2.3 on 2019-09-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_memebers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, verbose_name='id задачи в системе')),
                ('verbose_key', models.CharField(max_length=200, verbose_name='Нормальное название задачи')),
                ('type', models.IntegerField(verbose_name='Тип задачи')),
            ],
            options={
                'db_table': 'jira_issue',
            },
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_login', models.CharField(max_length=200, verbose_name='логин в jira')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_memebers.TeamMember', verbose_name='Ссылка на тиммембера')),
            ],
            options={
                'db_table': 'jira_user',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.IntegerField(verbose_name='Затраченное время в секундах')),
                ('date', models.DateField(verbose_name='Когда залогировано время')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira_integration.Issue', verbose_name='Ссылка на задачу')),
                ('jira_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira_integration.JiraUser', verbose_name='Ссылка на jira_user')),
            ],
            options={
                'db_table': 'jira_worklog',
            },
        ),
    ]
