# Generated by Django 2.2.3 on 2019-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование')),
                ('uid', models.CharField(max_length=400, verbose_name='id в Jira')),
            ],
            options={
                'db_table': 'jira_issuetype',
            },
        ),
    ]
