# Generated by Django 2.2.3 on 2019-09-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0002_issuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jira_integration.IssueType', verbose_name='Ссылка на тип'),
        ),
    ]
