# Generated by Django 2.2.3 on 2019-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0003_auto_20190902_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='original_estimate',
            field=models.IntegerField(default=0, verbose_name='Первоначальная оценка'),
        ),
    ]
