# Generated by Django 2.2.3 on 2019-09-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0004_issue_original_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа списания')),
            ],
            options={
                'db_table': 'jira_worklogtype',
            },
        ),
        migrations.AddField(
            model_name='worklog',
            name='worklog_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jira_integration.WorklogType', verbose_name='Тип списания'),
        ),
    ]
