# Generated by Django 2.2.3 on 2019-09-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0007_auto_20190904_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jira_integration.IssueType', verbose_name='Ссылка на тип'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uid',
            field=models.CharField(max_length=200, null=True, verbose_name='id задачи в системе'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='verbose_key',
            field=models.CharField(max_length=200, null=True, verbose_name='Нормальное название задачи'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='name',
            field=models.CharField(max_length=400, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='uid',
            field=models.CharField(max_length=400, null=True, verbose_name='id в Jira'),
        ),
        migrations.AlterField(
            model_name='jirauser',
            name='jira_login',
            field=models.CharField(max_length=200, null=True, verbose_name='логин в jira'),
        ),
        migrations.AlterField(
            model_name='jirauser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base_memebers.TeamMember', verbose_name='Ссылка на тиммембера'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(null=True, verbose_name='Когда залогировано время'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jira_integration.Issue', verbose_name='Ссылка на задачу'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='jira_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jira_integration.JiraUser', verbose_name='Ссылка на jira_user'),
        ),
        migrations.AlterField(
            model_name='worklogtype',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование типа списания'),
        ),
    ]
