# Generated by Django 2.2.3 on 2019-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0008_auto_20190904_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingJiraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Когда началась загрузка')),
                ('jql', models.CharField(max_length=255, null=True, verbose_name='JQL запроса')),
                ('data_count', models.IntegerField(null=True, verbose_name='Сколько было загружено данных по JQL')),
            ],
            options={
                'db_table': 'jira_loading_information',
            },
        ),
    ]
