# Generated by Django 2.2.3 on 2019-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0009_loadingjirainformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingjirainformation',
            name='data_type',
            field=models.IntegerField(null=True, verbose_name='Тип данных'),
        ),
    ]
