# Generated by Django 2.2.3 on 2020-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(verbose_name='Дата выходного/праздника')),
                ('sokr', models.BooleanField(verbose_name='True - сокращенный день False - полностью выходной')),
            ],
            options={
                'db_table': 'calendar_holidays',
            },
        ),
        migrations.AddIndex(
            model_name='holidays',
            index=models.Index(fields=['holiday_date'], name='calendar_ho_holiday_fbb0dd_idx'),
        ),
    ]
