# Generated by Django 2.2.3 on 2019-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
            options={
                'db_table': 'tm_team_member',
            },
        ),
    ]
